server:
  port: 9901
eureka:
  instance:
    preferIpAddress: true
    instance-id: data
  client:
    serviceUrl:
      defaultZone: http://localhost:9900/eureka/

spring:
  application:
    name: server-service  #表示微服务的名称
  cloud:
    loadbalancer:
      retry:
        enabled: false